apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-1.17
  name: nginx-1.17
  namespace: test-ac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1.17
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1.17
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        resources: {}
status: {}
